RubyBlog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"

  resources :categories, only: [:show]


end

RubyBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RubyBlog/app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

RubyBlog/app/models/post.rb
class Post < ApplicationRecord
    
    belongs_to :user
    belongs_to :category

    scope :with_categories, -> {includes(:category)}
    scope :ordered, -> {order(id: :desc)}    

    def self.find_by_category_id(category_id)
        where(category_id: category_id)
    end
end

RubyBlog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

RubyBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RubyBlog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @categories = Category.all
    @posts = Post.all.ordered.with_categories
    @posts = @posts.find_by_category_id(params[:id])
  end

end

RubyBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
      @posts = Post.ordered.with_categories
      @categories = Category.all
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end


  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :category_id)
    end
end

RubyBlog/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 

	private

	def sign_up_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end

end

RubyBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyBlog/app/helpers/posts_helper.rb
module PostsHelper
end

RubyBlog/app/views/categories/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-three-quarters">
        <div class="rows">
          <%= render 'layouts/postInfo' %>
        </div>   
      </div>
      <div class="column">
        <div class="rows">
          <%= render "layouts/categoryBar" %>
        </div> 
        <p>
          <%= link_to 'Back to all', posts_path %>
        </p>
      </div>
    </div>
  </div>
</section>

RubyBlog/app/views/layouts/_categoryBar.html.erb
<h2 class="title is-4">Категорії на даний момент</h2>
<% @categories.each do | category | %>

  <p>
    <%= link_to category.name, category_path(category.id) %>
  </p>
  
<% end %>

RubyBlog/app/views/layouts/_postInfo.html.erb
<% @posts.each do | post | %>
  <div class="box">
  	<article class="media">
  		<div class="media-content">
  			<div class="content">
				<div class="columns">
				<div class="column post">
					<h1 class="post-title"><%= post.title %></h1>	
					<p class="post-title"><i>Category: <%= post.category.name %></i></p>
				</div>		
				<div class="column post ">
					<p class="is-pulled-right has-text-grey	posted-by"><%= post.created_at.strftime("%B %d, %Y") %></p>
					<p class="is-pulled-right">Posted by <%= post.user.username%></p>
				</div>					  
			  </div>
				<div class="post-content">
					<p><%= post.content.slice(0, 10) %>...</p>
				</div>
  			</div>
     
  			<nav class="level">
  				<div class="level-left">
  					<%= link_to post, class: "level-item" do %>
  					  <button class="button is-success">Read all</button>
  					<% end %>
				</div>
				            <% if (user_signed_in? && current_user.username.eql?(post.user.username))%>

					<div class="level-right">
						<%= link_to edit_post_path (post), class: "level-item" do %>
						<button class="button is-warning">Edit</button>
						<% end %>
						<%= link_to post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do %>
							<button class="button is-danger">Delete</button>
						<% end %>
					</div>
			<% end%>
  			</nav>
  		</div>
  	</article>
  </div>
<% end %>

RubyBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
  		<div class="notification is-link global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>
    <nav class="navbar is-primary">
  		<div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item" do %>
  			<h1 class="title is-5">Naza_blog</h1>
  		<% end %>
  	 </div>

				<div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
          <div class="navbar-item">
					<div class="field is-grouped">

            <% if user_signed_in? %>
            	<p class="control">
							  <%= link_to 'New post', new_post_path, class: "button is-info is-inverted" %>
						  </p>
              <p class="control">
                <%= link_to current_user.username, edit_user_registration_path, class: "button is-primary" %>
              </p>
              <p>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"button is-primary" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Log In', new_user_session_path, class: "button is-primary" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-primary" %>
            </p>
            <% end %>
            </div>
					</div>
				</div>
			</div>
  	</nav>
    
    <%= yield %>
  </body>
</html>

RubyBlog/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <label class="label"><%= form.label :title %></label>
  
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="field">
     <label class="label">  <%= form.label :content %></label>

  
    <%= form.text_area :content, class: "textarea"%>
  </div>

    <div class="field">
       <label class="label"><%= form.label :category%></label>


 
      <%= form.collection_select :category_id, Category.all, :id, :name  %>
    </div>

  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

RubyBlog/app/views/posts/_postInfo.html.erb
<% @posts.each do | post | %>
  <div class="box">
  	<article class="media">

  		<div class="media-content">
  			<div class="content">

	

				<div class="columns">
				<div class="column post">
					<h1 class="post-title"><%= post.title %></h1>	
					<p class="post-title"><i><%= post.category.name %></i></p>
				</div>		
				<div class="column post ">
					<p class="is-pulled-right has-text-grey	posted-by"><%= post.created_at.strftime("%B %d, %Y") %></p>
					<p class="is-pulled-right">Posted by <%= post.user.username%></p>
				</div>					  
			  </div>
				<div>
					<p><%= post.content %></p>
				</div>



  			</div>
     
  			<nav class="level">
  				<div class="level-left">
  					<%= link_to post, class: "level-item" do %>
  					  <button class="button is-success">Go to post</button>
  					<% end %>
				</div>
				            <% if (user_signed_in? && current_user.username.eql?(post.user.username))%>

					<div class="level-right">
						<%= link_to edit_post_path (post), class: "level-item" do %>
						<button class="button is-warning">Edit</button>
						<% end %>
						<%= link_to post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do %>
							<button class="button is-danger">Delete</button>
						<% end %>
					</div>
			<% end%>
  			</nav>

  		</div>
  	</article>
  </div>
<% end %>

RubyBlog/app/views/posts/edit.html.erb
<h1 class="title">Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

RubyBlog/app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <div class="rows">
       <%= render 'postInfo' %>
       <%= render 'categoryBar' %>
    </div>
  </div>
</section>

RubyBlog/app/views/posts/new.html.erb
<h1 class="title">New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

RubyBlog/app/views/posts/show.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <div class="columns">
          <div class="column post">
            <h1 class="post-title"><%= @post.title %></h1>	
            <p class="post-title"><i>Category: <%= @post.category.name %></i></p>
          </div>		
          <div class="column post ">
            <p class="is-pulled-right has-text-grey	posted-by"><%= @post.created_at.strftime("%B %d, %Y") %></p>
            <p class="is-pulled-right">Posted by <%= @post.user.username%></p>
          </div>					  
          </div>
        <div class="post-content">
          <p><%= @post.content%></p>
        </div>
      </div>
    </div>
    
  </article>
  <%= link_to 'Back', posts_path %> 
</div>